version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=axon
      - POSTGRES_USER=axon
      - POSTGRES_PASSWORD=axon
      - MAX_CONNECTIONS=300
    networks:
      - custom

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - custom

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "axon-events:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.66.81.0/24
